services:
  - type: web
    name: andromed-bingo-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webapp_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    ports:
      - port: 5000

  - type: worker
    name: lucy-bingo-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python advanced_bot.py