services:
  # Web service for Flask API
  - type: web
    name: andromeda-bingo-api
    runtime: python
    repo: https://github.com/Getnet458/andromeda-bingo-bot
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  # Worker service for Telegram Bot
  - type: worker
    name: andromeda-bingo-bot
    runtime: python
    repo: https://github.com/Getnet458/andromeda-bingo-bot
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python advanced_bot.py